compressionLevel: mixed

enableScripts: true

httpProxy: "${http_proxy:-}"

httpsProxy: "${https_proxy:-}"

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1108110
  - 1108111

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  proton:
    npmRegistryServer: "https://registry.npmjs.org"
  proton-meet:
    npmRegistryServer: "https://registry.npmjs.org"

plugins:
  - path: .yarn/plugin-postinstall.js

yarnPath: .yarn/releases/yarn-4.12.0.cjs
