package srp

import (
	"testing"
)

// TestBcryptCrossValidation verifies our bcrypt implementation matches
// the bcryptjs library used by the Proton frontend.
// Test vectors generated by: node cross-validate.mjs
func TestBcryptCrossValidation(t *testing.T) {
	// From Node.js bcryptjs:
	// salt = [1,2,3,4,5,6,7,8,9,10]
	// password = "testpass"
	// first16 = salt + "proton" = [1,2,3,4,5,6,7,8,9,10, 'p','r','o','t','o','n']
	// encodedSalt = ".OGB/.SE/ueHAl/wZ1PtZe"
	// bcryptResult = "$2y$10$.OGB/.SE/ueHAl/wZ1PtZeKCDomD1Hvn4udz2uUrN73XbK06L9sEq"

	password := "testpass"
	first16 := []byte{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 'p', 'r', 'o', 't', 'o', 'n'}

	// Test bcrypt base64 encoding
	encoded := bcryptBase64Encode(first16)
	expectedEncoded := ".OGB/.SE/ueHAl/wZ1PtZe"
	if encoded[:22] != expectedEncoded {
		t.Fatalf("bcryptBase64Encode mismatch:\n  got:  %s\n  want: %s", encoded[:22], expectedEncoded)
	}

	// Decode the encoded salt back to raw bytes
	rawSalt := bcryptBase64Decode(encoded[:22], 16)
	if len(rawSalt) != 16 {
		t.Fatalf("decoded salt length: got %d, want 16", len(rawSalt))
	}
	for i := range first16 {
		if rawSalt[i] != first16[i] {
			t.Fatalf("decoded salt mismatch at byte %d: got %d, want %d", i, rawSalt[i], first16[i])
		}
	}

	// Test full bcrypt hash
	result, err := bcryptWithSalt([]byte(password), rawSalt)
	if err != nil {
		t.Fatalf("bcryptWithSalt: %v", err)
	}

	expectedResult := "$2y$10$.OGB/.SE/ueHAl/wZ1PtZeKCDomD1Hvn4udz2uUrN73XbK06L9sEq"
	if result != expectedResult {
		t.Fatalf("bcrypt result mismatch:\n  got:  %s\n  want: %s", result, expectedResult)
	}
}
